services:
  router:
    container_name: router
    build:
      context: .
      file: Dockerfile.stun
      target: base
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      private_net:
        ipv4_address: 192.168.100.200
      public_net:
        ipv4_address: 192.168.200.200
    volumes:
      - ./scripts/router.sh:/router.sh
    command: bash -c "./router.sh && tail -f /dev/null"

  server:
    container_name: server
    build:
      context: .
      file: Dockerfile.stun
      target: e2e
    networks:
      public_net:
        ipv4_address: 192.168.200.100
    volumes:
      - ./e2e/stun-ts:/app
      - /app/node_modules
    command: pnpm dev

  client:
    container_name: client
    build:
      context: .
      file: Dockerfile.stun
      target: e2e
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      private_net:
        ipv4_address: 192.168.100.100
    volumes:
      - ./e2e/stun-ts:/app
      - node_modules:/app/node_modules
      - ./scripts/client.sh:/app/client.sh
    # TODO: wait for server and router to be ready stably
    command: bash -c "/app/client.sh && sleep 3 && pnpm test:docker"
    depends_on:
      - server
      - router

volumes:
  node_modules:

networks:
  private_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  public_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24

